import { expect, test } from '@playwright/test';
import { mealConfirmResponseSchema, mealDraftMatchResponseSchema, mealDraftRevisionResponseSchema } from '@ev/contracts';

test('desktop server MVP edits a disclosed meal candidate and confirms a sourced meal through the BFF', async ({ page }, testInfo) => {
  test.setTimeout(60_000);
  const problems: string[] = [];
  page.on('pageerror', (error) => problems.push(error.message));
  page.on('console', (message) => { if (message.type() === 'error') problems.push(message.text()); });
  await page.goto('/setup');
  await page.getByLabel('用户名').fill('server-mvp-owner');
  await page.getByLabel('密码').fill('synthetic-server-mvp-password');
  await page.getByRole('button', { name: '创建本地账号' }).click();
  await expect(page).toHaveURL(/\/today$/);
  await page.goto('/settings/providers');
  const settings = page.getByRole('region', { name: '营养数据：USDA FoodData Central' });
  await settings.getByLabel('USDA API key').fill('synthetic-usda-key');
  await settings.getByRole('button', { name: '保存营养数据密钥' }).click();
  await expect(settings.getByText('密钥已保存；尚未发起数据查询')).toBeVisible();
  await expect(settings.getByLabel('USDA API key')).toHaveValue('');

  await page.goto('/nutrition');
  await page.getByLabel('餐食文本', { exact: true }).fill('Fixture Food Alpha 150 g');
  await expect(page.getByRole('button', { name: '解析候选食物' })).toBeDisabled();
  await page.getByLabel('我理解解析会向已配置的 DeepSeek 发送餐食文本。', { exact: true }).check();
  await page.getByRole('button', { name: '解析候选食物' }).click();
  await page.getByLabel('候选 1 十进制数量', { exact: true }).fill('200');
  await expect(page.getByRole('button', { name: '匹配营养来源' })).toBeDisabled();
  const editedResponse = page.waitForResponse((response) => response.request().method() === 'POST' && /\/meal-drafts\/[^/]+\/revisions$/.test(new URL(response.url()).pathname));
  await page.getByRole('button', { name: '保存候选修改' }).click();
  const edited = mealDraftRevisionResponseSchema.parse(await (await editedResponse).json()).data;
  expect(edited.revision.candidates[0]?.quantityDecimal).toBe('200');
  const matchResponse = page.waitForResponse((response) => response.request().method() === 'POST' && /\/meal-drafts\/[^/]+\/matches$/.test(new URL(response.url()).pathname));
  await page.getByRole('button', { name: '匹配营养来源' }).click();
  const matched = mealDraftMatchResponseSchema.parse(await (await matchResponse).json()).data;
  const snapshot = matched.matches[0]?.snapshots[0];
  expect(snapshot).toBeDefined();
  expect(snapshot?.source.sourceKind).toBe('TEST_FIXTURE');
  await page.getByLabel('为 Fixture Food Alpha 选择来源').selectOption(snapshot!.id);
  await page.getByRole('button', { name: '保存来源选择' }).click();
  await expect(page.getByRole('button', { name: '确认这餐' })).toBeEnabled();
  const confirmedResponse = page.waitForResponse((response) => response.request().method() === 'POST' && /\/meal-drafts\/[^/]+\/confirm$/.test(new URL(response.url()).pathname));
  await page.getByRole('button', { name: '确认这餐' }).click();
  const confirmed = mealConfirmResponseSchema.parse(await (await confirmedResponse).json()).data;
  expect(confirmed.meal.totals).toEqual({ energyKcalDecimal: '200', proteinGramsDecimal: '20', carbohydrateGramsDecimal: '40', fatGramsDecimal: '10' });
  await expect(page.getByRole('heading', { name: '餐食已确认' })).toBeVisible();
  await page.reload();
  await page.getByRole('button', { name: '读取本地餐食草稿' }).click();
  await page.getByRole('button', { name: `打开餐食草稿 ${edited.draft.id}` }).click();
  await expect(page.getByText('200 kcal · 蛋白质 20 g · 碳水 40 g · 脂肪 10 g')).toBeVisible();
  expect(problems).toEqual([]);
  await testInfo.attach('server-mvp-meal-lineage', { contentType: 'application/json', body: JSON.stringify({ evidence: 'AUTOMATED_TEST_FIXTURE', draftId: edited.draft.id, meal: confirmed.meal, source: snapshot!.source, record: snapshot!.record, browserErrors: problems }) });
});
